//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univie.Assistant.Crawler.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Univie.Assistant.Crawler.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;structure current=&quot;2022S&quot; local=&quot;false&quot; graceperiod=&quot;false&quot; version=&quot;2022-01-14T01:04:00+01:00&quot;&gt;&lt;module id=&quot;274408&quot; level=&quot;1&quot; spl=&quot;40&quot; path=&quot;267803|274408&quot; when=&quot;2022S&quot;&gt;&lt;predecessor path=&quot;260036|267343&quot; when=&quot;2021W&quot;/&gt;&lt;offeredby id=&quot;8540&quot;&gt;SPL 40 - Doktoratsstudium Sozialwissenschaften&lt;/offeredby&gt;&lt;title xml:lang=&quot;de&quot;&gt;Studienprogrammleitung 40 - Doktoratsstudium Sozialwissenschaften&lt;/title&gt;&lt;title xml:lang=&quot;en&quot;&gt;40 - Doctoral Directorate of Studies Social Sciences&lt;/title&gt;&lt;courses&gt;&lt;/courses&gt;&lt;exams&gt;&lt;/exams&gt;&lt;modul [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Browse_274408 {
            get {
                return ResourceManager.GetString("Browse_274408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;course id=&quot;350172&quot; when=&quot;2022S&quot; local=&quot;false&quot; graceperiod=&quot;false&quot; version=&quot;2022-03-03T15:29:36+01:00&quot;&gt;&lt;longname xml:lang=&quot;de&quot;&gt;BC2I - Sport und Gesellschaft&lt;/longname&gt;&lt;longname xml:lang=&quot;en&quot;&gt;BC2I - Sports and Society&lt;/longname&gt;&lt;type desc=&quot;Vorlesung&quot;&gt;VO&lt;/type&gt;&lt;ects&gt;3.00&lt;/ects&gt;&lt;sws&gt;2.00&lt;/sws&gt;&lt;immanent&gt;false&lt;/immanent&gt;&lt;asexcluded&gt;false&lt;/asexcluded&gt;&lt;chapters&gt;&lt;codes&gt;BC2I&lt;/codes&gt;&lt;chapter path=&quot;267803|274286|274380|274290&quot;&gt;&lt;category xml:lang=&quot;de&quot; path=&quot;267803|274286|274380&quot;&gt;Erweiterungscurriculum Humanwissenschaft [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Course_350172 {
            get {
                return ResourceManager.GetString("Course_350172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///      
        ///    &lt;nav class=&quot;semester-navigation current&quot;&gt;
        ///    &lt;strong class=&quot;hidden&quot;&gt;Semesternavigation:&lt;/strong&gt; &lt;a href=&quot;?semester=2021W&quot; class=&quot;previous&quot;&gt;&lt;abbr title=&quot;Vorheriges Semester&quot;&gt;&lt;span class=&quot;hidden&quot;&gt;&amp;lt;&amp;lt;&lt;/span&gt;&lt;/abbr&gt;&lt;/a&gt;&lt;span class=&quot;separator hidden&quot;&gt; - &lt;/span&gt;&lt;span class=&quot;current&quot;&gt;2022S&lt;/span&gt;
        ///  &lt;/nav&gt;&lt;div class=&quot;usse-id-vvz&quot;&gt;
        ///    &lt;h2 class=&quot;icon-usse-info&quot;&gt;&lt;a class=&quot;name&quot; href=&quot;vvz_sub.html?from=1&amp;amp;to=2&amp;amp;semester=2022S&amp;amp;path=275574&quot;&gt;Besondere Lehrangebote&lt;/a&gt;&lt;/h2&gt;
        ///  &lt;div&gt;&lt;a class=&quot;l [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Main_HTML {
            get {
                return ResourceManager.GetString("Main_HTML", resourceCulture);
            }
        }
    }
}
